In [1]:
import numpy as np

In [2]:
benimdizi= np.arange(0,16)

In [3]:
benimdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
benimdizi[4:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
benimdizi[3:10] = 700

In [7]:
benimdizi

array([  0,   1,   2, 700, 700, 700, 700, 700, 700, 700,  10,  11,  12,
        13,  14,  15])

In [8]:
baskaDizi=np.arange(0,26)

In [9]:
slicingDizi= baskaDizi[3:8]

In [10]:
slicingDizi

array([3, 4, 5, 6, 7])

In [11]:
slicingDizi[:]=22

In [12]:
slicingDizi

array([22, 22, 22, 22, 22])

In [13]:
baskaDizi

array([ 0,  1,  2, 22, 22, 22, 22, 22,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [14]:
ornekDizi= np.arange(0,26)

In [15]:
ornekDizisiKopya= ornekDizi.copy()

In [16]:
ornekDizisiKopyaSlicing= ornekDizisiKopya[3:5]

In [17]:
ornekDizisiKopyaSlicing[:]=27

In [18]:
ornekDizisiKopyaSlicing

array([27, 27])

In [19]:
ornekDizisiKopya

array([ 0,  1,  2, 27, 27,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [20]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

## matrix

In [21]:
benimListem=[[10,20,30],[20,30,40],[30,40,50]]

In [22]:
benimMatrixDizi= np.array(benimListem)

In [23]:
benimMatrixDizi

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [24]:
benimMatrixDizi[0]

array([10, 20, 30])

In [25]:
benimMatrixDizi[1,1]

30

In [26]:
benimMatrixDizi[1][1]

30

In [27]:
benimMatrixDizi[1:,1]

array([30, 40])

In [28]:
benimMatrixDizi[[0,2]]

array([[10, 20, 30],
       [30, 40, 50]])

## opreasyonlar

In [29]:
yeniBirdizi=np.random.randint(1,100,20)

In [30]:
yeniBirdizi

array([89, 43, 58,  3,  3, 14, 40, 58, 79, 10, 31, 86, 26,  5, 16, 19, 96,
       57, 52, 90])

In [31]:
yeniBirdizi>24

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True,  True])

In [32]:
sonucDizi=yeniBirdizi>24

In [33]:
sonucDizi

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True,  True])

In [34]:
yeniBirdizi[sonucDizi]

array([89, 43, 58, 40, 58, 79, 31, 86, 26, 96, 57, 52, 90])

In [35]:
yeniBirdizi[yeniBirdizi>24]

array([89, 43, 58, 40, 58, 79, 31, 86, 26, 96, 57, 52, 90])

In [36]:
sondizi=np.arange(1,26)

In [37]:
sondizi + sondizi

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [38]:
sondizi* sondizi

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625])

In [39]:
np.sqrt(sondizi)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ])

In [40]:
np.max(sondizi)

25

In [41]:
np.min(sondizi)

1