In [1]:
import numpy as np

In [2]:
benimListem=[20,30,40]

In [3]:
np.array(benimListem)

array([20, 30, 40])

In [4]:
matrixListesi=[[20,30,40],[30,40,50],[40,50,60]]

In [5]:
np.array(matrixListesi)

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

## arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## linspace

In [13]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## eye

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [15]:
np.random.randn(5)

array([0.72949726, 1.15772094, 0.48802654, 0.68566087, 1.64483293])

In [16]:
np.random.randn(4,4)

array([[ 0.32417947, -1.76656243, -1.40607652,  1.11311005],
       [ 1.57128639, -0.01214112, -0.15987386, -0.3769289 ],
       [ 0.12308559, -0.06879974, -0.14264035,  1.10511786],
       [ 0.23817734,  0.62934804, -0.66049475,  0.07625988]])

In [17]:
np.random.randint(1,10)

8

In [18]:
np.random.randint(1,20,5)

array([ 5, 18,  2, 13, 19])

In [19]:
benimNumpyDizim=np.arange(6)

In [20]:
benimNumpyDizim

array([0, 1, 2, 3, 4, 5])

In [21]:
benimRandomDizim=np.random.randint(0,100,30)

In [22]:
benimRandomDizim

array([10, 62,  3, 14, 27, 46, 12, 41, 17, 40, 74, 63, 38, 60, 75, 56, 16,
       32, 14, 67, 23, 19, 88, 80, 76, 34, 73, 79, 25, 84])

## numpy dizi methodları

In [26]:
benimNumpyDizim.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
benimNumpyDizim.max()

5

In [28]:
benimNumpyDizim.min()

0

In [29]:
benimRandomDizim.min()

3

In [30]:
benimRandomDizim.max()

88

In [31]:
benimRandomDizim.argmax()

22

In [32]:
benimRandomDizim.argmin()

2

In [33]:
benimNumpyDizim.shape

(6,)